### ISSUE TITLE
Use of uninitialized value $list in pattern match (m//) at PERL2EXE_STORAGE/utf8_heavy.pl

### ISSUE THREAD

**Issue by SanketBaraiya** [Silv3rHorn/autoripy#6]
This warning shows up in console every time MALWARE category is executed. Below are the logs:

---- Processing the EXECUTION category
---- Processing the USER_CONFIG category
---- Processing the WEB category
---- Processing the COMM category
---- Processing the OS category
---- Processing the SOFTWARE category
---- Processing the USER_ACT category
---- Processing the MALWARE category
	Use of uninitialized value $list in pattern match (m//) at PERL2EXE_STORAGE/utf8_heavy.pl line 399.
---- Processing the AUTORUNS category
---- Processing the STORAGE category
---- Processing the LOG category
---- Processing the NETWORK category
---- Processing the USER_NETWORK category
---- Processing the USER_VIRTUAL category
---- Processing the USER_FILE category
---- Processing the USERS category
---- Processing the DEVICE category

**Comment by CmdrBurrito** [comment]
Hi Sanket,

FYI, the "Use of uninitialized value $list in pattern match (m//) at PERL2EXE_STORAGE ..." Warning Message is generated by specific RegRipper plugins that use the "PERL2EXE_STORAGE" Perl module (e.g., the current "fileless.pl" and "shares.pl" plugins, as well as the deprecated "mspaper.pl", "internet_settings_cu.pl" and "internet_explorer_cu.pl" plugins).  

For more details, see the report at:
https://github.com/keydet89/RegRipper4.0/issues/1#issuecomment-1930639464

As a result, Harlan Carvey (keydet89), who is the author of RegRipper, would have to fix the specific RR plugins that generate those warning messages, rather than Silv3rHorn, who is the author of "autoripy".  

However, please note that since those Warning Messages do not affect the actual "execution" of those specific RegRipper plugins, Harlan is generally not amenable to troubleshooting or attempting to fix them.  As such, requests to Harlan to "fix" any plugins that generate such warning messages, are likely to fall on deaf ears (and perhaps rightly so).  Only "errors" that affect actual RR plugin functionality will get attention.

**Comment by CmdrBurrito** [comment]
FYI, in this case it is specifically the RegRipper (RR) plugin "fileless.pl" that generates the warning message in question, whenever "autoripy" runs that plugin as part of its MALWARE category.  

Interestingly, the "fileless.pl" RR plugin classifies itself as belonging to a category named "persistence", rather than to the "malware" category name that "autoripy" bundles its output under. but that is neither here nor there.

**Comment by SanketBaraiya** [comment]
Thanks I will see into it.
